### ISSUE TITLE
Crash when entering data

### ISSUE THREAD

**Issue by hspagnolo** [kengruven/strukt-bugs#39] opened 2020-04-29 08:06 UTC
Hi Ken,

[Strukt_2020-04-29-095334_hsp.crash.zip](https://github.com/kengruven/strukt-bugs/files/4550430/Strukt_2020-04-29-095334_hsp.crash.zip)

I just install the new version from the MAS (1.7.0) and I use Catalina 10.15.4

Every time I press "enter" to validate the data entering, Strukt crash (eg, I add "List Files", then "folder", I type the folder name, then press "enter")

See the crash log.

Thanks and regards
Henri

**Comment by kengruven** [comment] 2020-04-29 17:55
Thanks for the crash report.  I'm looking in to this today.

Does this crash occur with other operation types, like "Literal Value"?  "List Files" is more complex than most because it has to deal with security.

**Comment by hspagnolo** [comment] 2020-04-29 18:40
Hi Ken,

Yes it happens also with Literal Value.

Regards
Henri

**Comment by kengruven** [comment] 2020-04-30 14:08
This is a strange bug.  The stack trace doesn't pinpoint a specific line of code, but it does tell me what method crashed, and it's a short and simple method that doesn't really do anything risky.

Two crazy questions:

- Does "undo" work at all?  For example, when you open one of the Sample pipelines, delete an operation, does the Edit menu say "Undo Delete Operation"?  Or does deleting an operation crash, too?

- Do you have a pretty old Mac (older than 2014, maybe), by any chance?

**Comment by hspagnolo** [comment] 2020-04-30 14:29
Hi Ken

1) yes undo works and deleting operation also, no crash
2) Yes iMac late 2012 under Catalina 10.15.4 (so does this mean it is hardware problem?)

Thanks and regards
Henri

**Comment by kengruven** [comment] 2020-05-20 19:16
I haven’t been very responsive on this, and I apologize.  This past month has been weird.

I can't reproduce the bug here, but I don't have the exact environment, either.  I don’t think it’s hardware related (there's no reason it should be), though of course that's impossible to rule out entirely.

The stack trace shows it’s crashing in a pretty simple function.  Internally, the compiler inserts the “ud2” (“undefined”) opcode at the end of functions, and jumps to that when an assumption is violated.  There’s 3 ways this particular function can get there.  One is if the UndoManager were nil, and since you report that Undo works in other cases, that’s not the cause here.

The other 2 cases are looking up the operation and flag in their respective arrays, and I don’t see how that can occur.  It only gets to this function from one place, which computes the array indices by looking in the arrays.  That is, it’s essentially doing “find the array index of this operation, and then call another function which looks up this operation by array index" (all in the main thread).  If it were missing, it should have failed in the first function!

Here's my plan going forward.  For 1.7.1, I’m switching from `NSLog` to `os_log` ("Apple Unified Logging").  Updating the logging was on my to-do list, anyway.  I’ll also put extra logging in this particular path.  Then you will be able to run a command in the Terminal like:

    log stream --predicate 'process == "Strukt"' --level debug

and see a bunch of junk that might help me figure out what's going on.  (You can run that today, but it'll probably only show a bunch of system junk.)

**Comment by hspagnolo** [comment] 2020-05-20 20:23
Hi Ken,

Hope the "weird" is not health related.

Thanks for your explanation. I run your process into the terminal see file attached.

Regards
Henri
[terminal process.txt](https://github.com/kengruven/strukt-bugs/files/4659090/terminal.process.txt)

**Comment by kengruven** [comment] 2020-05-21 18:23
You've got to wait for 1.7.1 to be released!  :-)

**Comment by hspagnolo** [comment] 2020-05-21 18:29
No hurry Ken, thanks

**Comment by kengruven** [comment] 2020-05-22 16:10
Strukt 1.7.1 is now live on the Mac App Store.  There's extra logging when you edit a flag value, which should help me narrow down what's going on here.

**Comment by hspagnolo** [comment] 2020-05-22 17:29
Hi Ken,

Downloaded, thanks. Please find attached the terminal process. I just try to add for List Files the "folder" flag and it crash.

Regards
Henri
[strukt_process.txt](https://github.com/kengruven/strukt-bugs/files/4669459/strukt_process.txt)

**Comment by kengruven** [comment] 2020-06-11 19:58
Good news!  I think I've figured this out.  You're using the right-click menu to add the flag, right?  I completely missed that.  (Keyboard-only entry came first, so that's what I had been trying.  My mistake.)  95% of the two paths are obviously the same, but there was a small but nasty bug in the mouse-handling part of this -- but it was not in the stack trace at the time of the crash, which threw me off.

I believe I've fixed this issue, and the fix will be in the next version of Strukt (1.7.2).  In the meantime, you can press the `-` key (or use the Edit -> Insert Flag menu item) to insert a flag and edit it without crashing.

**Comment by kengruven** [comment] 2020-06-14 21:57
Hello again!  Strukt 1.7.2 is now available on the Mac App Store.  I *think* it should resolve the bug you found.

**Comment by hspagnolo** [comment] 2020-06-15 05:16
Hi Ken,

Thanks for this new version. It works, I have been able to enter new flags without crash.

Again thanks for your support.

Regards
Henri

**Comment by kengruven** [comment] 2020-06-15 05:32
Excellent!

**Closed by kengruven** 2020-06-15 05:32 UTC
Labels: bug
